// netlify/functions/shared/universe-history.ts
//
// Point-in-time historical index membership.
//
// Phase 4's backtest is exposed to survivorship bias if its universe is
// "current S&P 500 constituents" — the companies that got delisted,
// acquired, or dropped from the index don't appear, and they're
// disproportionately the losers. This module answers questions like
// "was AAPL in the S&P 500 on 2018-03-15?" deterministically.
//
// Granularity: month-end snapshots. Sufficient for the quarterly /
// monthly rebalance frequencies TradeIQ actually backtests. Daily
// resolution is a six-figure data product.
//
// Source maintenance: the static UNIVERSE_HISTORY array below is
// generated by `scripts/generate-universe-history.ts`. See
// `docs/UNIVERSE_HISTORY_RUNBOOK.md` for refresh instructions.
//
// Coverage status (audit-time):
//   - Dow:     2018-01-31 → 2026-04-30, monthly. 100+ snapshots,
//              hand-curated against publicly documented index changes.
//   - SP500:   2026-04-30 only (current seed). Needs generator-script
//              run from a non-restricted env to extend.
//   - NDX:     2026-04-30 only (current seed). Same as SP500.
//   - Russell2k: 2026-04-30 only (current seed). iShares CSV scrape
//                required for historical depth.
//
// Phase 3 ships the framework correct and Dow at full coverage; SP500 /
// NDX / Russell history extension is a runbook task in any non-egress-
// restricted environment.
//
// PIT-cacheable: every lookup is a pure function of (index, date).

import { UNIVERSE } from './universe';

export type UniverseIndex = 'sp500' | 'ndx' | 'dow' | 'russell2k';

export interface UniverseSnapshot {
  /** YYYY-MM-DD month-end. */
  date: string;
  index: UniverseIndex;
  /** Sorted alphabetically for deterministic comparison. */
  tickers: string[];
}

// ---------------------------------------------------------------------------
// Dow Jones Industrial Average — full historical curation
// ---------------------------------------------------------------------------
//
// Documented index changes used to walk back from current:
//   2024-02-26  AMZN replaces WBA (Walgreens)
//   2024-11-08  NVDA replaces INTC; SHW replaces DOW
//   2020-08-31  AMGN, HON, CRM added; XOM, PFE, RTX removed
//   2019-04-02  Dow Inc replaced DowDuPont (DWDP→DOW)
//   2018-06-26  WBA replaces GE
//
// Building the Dow series: start from 2026-04-30 (current per universe.ts)
// and apply each pre-asOfDate change in reverse.

// Dow-30 reference snapshots (hand-curated):
const DOW_2026_04_30 = [
  'AAPL','AMGN','AMZN','AXP','BA','CAT','CRM','CSCO','CVX','DIS',
  'GS','HD','HON','IBM','JNJ','JPM','KO','MCD','MMM','MRK',
  'MSFT','NKE','NVDA','PG','SHW','TRV','UNH','V','VZ','WMT',
];

const DOW_2024_11_08_PRE = [
  // Same as above but INTC instead of NVDA, DOW instead of SHW
  'AAPL','AMGN','AMZN','AXP','BA','CAT','CRM','CSCO','CVX','DIS',
  'DOW','GS','HD','HON','IBM','INTC','JNJ','JPM','KO','MCD',
  'MMM','MRK','MSFT','NKE','PG','TRV','UNH','V','VZ','WMT',
];

const DOW_2024_02_26_PRE = [
  // WBA in place of AMZN, INTC in place of NVDA, DOW in place of SHW
  'AAPL','AMGN','AXP','BA','CAT','CRM','CSCO','CVX','DIS','DOW',
  'GS','HD','HON','IBM','INTC','JNJ','JPM','KO','MCD','MMM',
  'MRK','MSFT','NKE','PG','TRV','UNH','V','VZ','WBA','WMT',
];

const DOW_2020_08_31_PRE = [
  // Pre-Aug-2020: PFE, RTX, XOM in; AMGN, HON, CRM not yet in.
  // Plus pre-Feb-2024 (WBA), pre-Nov-2024 (INTC, DOW)
  'AAPL','AXP','BA','CAT','CSCO','CVX','DIS','DOW','GS','HD',
  'IBM','INTC','JNJ','JPM','KO','MCD','MMM','MRK','MSFT','NKE',
  'PFE','PG','RTX','TRV','UNH','V','VZ','WBA','WMT','XOM',
];

const DOW_2019_04_02_PRE = [
  // Pre-Apr-2019: DWDP (DowDuPont) instead of DOW
  'AAPL','AXP','BA','CAT','CSCO','CVX','DIS','DWDP','GS','HD',
  'IBM','INTC','JNJ','JPM','KO','MCD','MMM','MRK','MSFT','NKE',
  'PFE','PG','RTX','TRV','UNH','V','VZ','WBA','WMT','XOM',
];

const DOW_2018_06_26_PRE = [
  // Pre-Jun-2018: GE in, WBA not in. DowDuPont (DWDP) was in.
  'AAPL','AXP','BA','CAT','CSCO','CVX','DIS','DWDP','GE','GS',
  'HD','IBM','INTC','JNJ','JPM','KO','MCD','MMM','MRK','MSFT',
  'NKE','PFE','PG','RTX','TRV','UNH','V','VZ','WMT','XOM',
];

/**
 * Generate Dow month-end snapshots over a span by stepping forward and
 * applying changes at their effective dates.
 */
function generateDowHistory(): UniverseSnapshot[] {
  // Each row: change effective date, the constituent set IN EFFECT
  // FROM that date forward (until the next change).
  const segments: Array<{ from: string; tickers: string[] }> = [
    { from: '2018-01-31', tickers: DOW_2018_06_26_PRE },
    { from: '2018-06-26', tickers: DOW_2019_04_02_PRE },
    { from: '2019-04-02', tickers: DOW_2020_08_31_PRE },
    { from: '2020-08-31', tickers: DOW_2024_02_26_PRE },
    { from: '2024-02-26', tickers: DOW_2024_11_08_PRE },
    { from: '2024-11-08', tickers: DOW_2026_04_30 },
  ];

  const out: UniverseSnapshot[] = [];
  // Walk every month-end from 2018-01-31 to 2026-04-30 inclusive.
  const start = new Date('2018-01-31T00:00:00Z');
  const end = new Date('2026-04-30T00:00:00Z');
  let d = new Date(start);
  while (d <= end) {
    const iso = d.toISOString().slice(0, 10);
    // Find the segment whose from <= iso, last one wins.
    let active = segments[0].tickers;
    for (const seg of segments) if (seg.from <= iso) active = seg.tickers;
    out.push({ date: iso, index: 'dow', tickers: [...active].sort() });
    // Advance to next month-end.
    const next = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 2, 0));
    d = next;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Current-snapshot seed for SP500 / NDX / Russell2k
// ---------------------------------------------------------------------------
//
// These are derived from the existing universe.ts at module load. The
// canonical SP500 has 503 constituents but TradeIQ's universe.ts is a
// curated working set (~210 SP500, ~70 NDX, ~2000 Russell). The seed
// represents "tickers TradeIQ tracks for this index as of 2026-04-30."
// Phase 4 backtests using these seeds will be limited to the tracked
// subset; the generator script extends coverage by pulling from the
// authoritative Wikipedia / iShares sources.

const SEED_DATE = '2026-04-30';

function tickersTaggedWith(tag: UniverseIndex): string[] {
  return [...UNIVERSE.filter((u) => u.indices.includes(tag)).map((u) => u.ticker)].sort();
}

// ---------------------------------------------------------------------------
// Combined static history
// ---------------------------------------------------------------------------

export const UNIVERSE_HISTORY: UniverseSnapshot[] = [
  ...generateDowHistory(),
  { date: SEED_DATE, index: 'sp500', tickers: tickersTaggedWith('sp500') },
  { date: SEED_DATE, index: 'ndx', tickers: tickersTaggedWith('ndx') },
  { date: SEED_DATE, index: 'russell2k', tickers: tickersTaggedWith('russell2k') },
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/**
 * Return the constituent set of `index` AS OF `date` (the latest
 * available month-end snapshot ≤ date).
 *
 * Returns null when no snapshot exists at or before `date` for this
 * index — i.e., the date precedes Phase 3's coverage window. Phase 4
 * code should distinguish null (no data) from [] (empty index, which
 * never happens for these indices but is a valid type).
 */
export function tickersInIndexOnDate(
  index: UniverseIndex,
  date: string,
): string[] | null {
  const candidate = UNIVERSE_HISTORY
    .filter((s) => s.index === index && s.date <= date)
    .sort((a, b) => b.date.localeCompare(a.date))[0];
  return candidate ? candidate.tickers : null;
}

/**
 * Was `ticker` a member of `index` on `date`?
 *
 * Returns:
 *   true  — ticker present in the latest snapshot ≤ date.
 *   false — ticker absent from that snapshot.
 *   null  — no snapshot covers this date for this index (data gap).
 *
 * Phase 4 backtests should treat null as "exclude from sample" rather
 * than "ticker not in index" to avoid spurious survivorship effects
 * during data-gap periods.
 */
export function wasInIndexOnDate(
  ticker: string,
  index: UniverseIndex,
  date: string,
): boolean | null {
  const set = tickersInIndexOnDate(index, date);
  if (set === null) return null;
  return set.includes(ticker);
}

/**
 * Coverage report — which date ranges have data per index. Used by the
 * runbook + tests to surface gaps.
 */
export function universeHistoryCoverage(): Record<
  UniverseIndex,
  { firstDate: string | null; lastDate: string | null; snapshotCount: number }
> {
  const out: Record<UniverseIndex, { firstDate: string | null; lastDate: string | null; snapshotCount: number }> = {
    sp500: { firstDate: null, lastDate: null, snapshotCount: 0 },
    ndx: { firstDate: null, lastDate: null, snapshotCount: 0 },
    dow: { firstDate: null, lastDate: null, snapshotCount: 0 },
    russell2k: { firstDate: null, lastDate: null, snapshotCount: 0 },
  };
  for (const snap of UNIVERSE_HISTORY) {
    const c = out[snap.index];
    c.snapshotCount += 1;
    if (c.firstDate === null || snap.date < c.firstDate) c.firstDate = snap.date;
    if (c.lastDate === null || snap.date > c.lastDate) c.lastDate = snap.date;
  }
  return out;
}
