// TradeIQ universe — S&P 500 + Nasdaq 100 + DJIA + Russell 2000 top 250.
// Tickers deduped across indices and tagged.

export type IndexTag = 'sp500' | 'ndx' | 'dow' | 'russell2k';

export interface UniverseEntry {
  ticker: string;
  name: string;
  sector: string;
  indices: IndexTag[];
}

export const SECTOR_ETFS: Record<string, string> = {
  Technology: 'XLK',
  Semiconductors: 'SOXX',
  'Consumer Discretionary': 'XLY',
  'Consumer Staples': 'XLP',
  Healthcare: 'XLV',
  Financials: 'XLF',
  Industrials: 'XLI',
  Energy: 'XLE',
  Communication: 'XLC',
  Utilities: 'XLU',
  Materials: 'XLB',
  'Real Estate': 'XLRE',
};

export const SPY = 'SPY';
export const QQQ = 'QQQ';
export const IWM = 'IWM';

type Row = [string, string, string, IndexTag[]];

const ROWS: Row[] = [
  ['AAPL','Apple','Technology',['sp500','ndx','dow']],
  ['MSFT','Microsoft','Technology',['sp500','ndx','dow']],
  ['NVDA','NVIDIA','Semiconductors',['sp500','ndx','dow']],
  ['AMZN','Amazon','Consumer Discretionary',['sp500','ndx','dow']],
  ['META','Meta Platforms','Communication',['sp500','ndx']],
  ['GOOGL','Alphabet A','Communication',['sp500','ndx']],
  ['GOOG','Alphabet C','Communication',['sp500','ndx']],
  ['BRK.B','Berkshire Hathaway','Financials',['sp500']],
  ['TSLA','Tesla','Consumer Discretionary',['sp500','ndx']],
  ['AVGO','Broadcom','Semiconductors',['sp500','ndx']],
  ['JPM','JPMorgan Chase','Financials',['sp500','dow']],
  ['LLY','Eli Lilly','Healthcare',['sp500']],
  ['V','Visa','Financials',['sp500','dow']],
  ['WMT','Walmart','Consumer Staples',['sp500','dow']],
  ['UNH','UnitedHealth','Healthcare',['sp500','dow']],
  ['XOM','Exxon Mobil','Energy',['sp500']],
  ['ORCL','Oracle','Technology',['sp500']],
  ['MA','Mastercard','Financials',['sp500']],
  ['PG','Procter & Gamble','Consumer Staples',['sp500','dow']],
  ['HD','Home Depot','Consumer Discretionary',['sp500','dow']],
  ['COST','Costco','Consumer Staples',['sp500','ndx']],
  ['JNJ','Johnson & Johnson','Healthcare',['sp500','dow']],
  ['NFLX','Netflix','Communication',['sp500','ndx']],
  ['BAC','Bank of America','Financials',['sp500']],
  ['ABBV','AbbVie','Healthcare',['sp500']],
  ['CRM','Salesforce','Technology',['sp500','dow']],
  ['KO','Coca-Cola','Consumer Staples',['sp500','dow']],
  ['CVX','Chevron','Energy',['sp500','dow']],
  ['TMUS','T-Mobile','Communication',['sp500','ndx']],
  ['WFC','Wells Fargo','Financials',['sp500']],
  ['AMD','AMD','Semiconductors',['sp500','ndx']],
  ['CSCO','Cisco','Technology',['sp500','ndx','dow']],
  ['MRK','Merck','Healthcare',['sp500','dow']],
  ['PEP','PepsiCo','Consumer Staples',['sp500','ndx']],
  ['LIN','Linde','Materials',['sp500','ndx']],
  ['ADBE','Adobe','Technology',['sp500','ndx']],
  ['NOW','ServiceNow','Technology',['sp500','ndx']],
  ['TMO','Thermo Fisher','Healthcare',['sp500']],
  ['IBM','IBM','Technology',['sp500','dow']],
  ['ACN','Accenture','Technology',['sp500']],
  ['DIS','Disney','Communication',['sp500','dow']],
  ['MCD',"McDonald's",'Consumer Discretionary',['sp500','dow']],
  ['GE','GE Aerospace','Industrials',['sp500']],
  ['ABT','Abbott','Healthcare',['sp500']],
  ['AXP','American Express','Financials',['sp500','dow']],
  ['INTU','Intuit','Technology',['sp500','ndx']],
  ['PM','Philip Morris','Consumer Staples',['sp500']],
  ['CAT','Caterpillar','Industrials',['sp500','dow']],
  ['ISRG','Intuitive Surgical','Healthcare',['sp500','ndx']],
  ['QCOM','Qualcomm','Semiconductors',['sp500','ndx']],
  ['GS','Goldman Sachs','Financials',['sp500','dow']],
  ['TXN','Texas Instruments','Semiconductors',['sp500','ndx']],
  ['CMCSA','Comcast','Communication',['sp500','ndx']],
  ['BKNG','Booking','Consumer Discretionary',['sp500','ndx']],
  ['RTX','RTX','Industrials',['sp500']],
  ['UBER','Uber','Industrials',['sp500']],
  ['NEE','NextEra Energy','Utilities',['sp500']],
  ['SPGI','S&P Global','Financials',['sp500']],
  ['MS','Morgan Stanley','Financials',['sp500']],
  ['HON','Honeywell','Industrials',['sp500','ndx','dow']],
  ['AMGN','Amgen','Healthcare',['sp500','ndx','dow']],
  ['PFE','Pfizer','Healthcare',['sp500']],
  ['LOW',"Lowe's",'Consumer Discretionary',['sp500']],
  ['T','AT&T','Communication',['sp500']],
  ['UNP','Union Pacific','Industrials',['sp500']],
  ['ELV','Elevance Health','Healthcare',['sp500']],
  ['BLK','BlackRock','Financials',['sp500']],
  ['COP','ConocoPhillips','Energy',['sp500']],
  ['LMT','Lockheed Martin','Industrials',['sp500']],
  ['PGR','Progressive','Financials',['sp500']],
  ['BX','Blackstone','Financials',['sp500']],
  ['SYK','Stryker','Healthcare',['sp500']],
  ['TJX','TJX Companies','Consumer Discretionary',['sp500']],
  ['DE','Deere','Industrials',['sp500']],
  ['SCHW','Charles Schwab','Financials',['sp500']],
  ['ETN','Eaton','Industrials',['sp500']],
  ['PLTR','Palantir','Technology',['sp500','ndx']],
  ['CB','Chubb','Financials',['sp500']],
  ['ADP','ADP','Industrials',['sp500','ndx']],
  ['VRTX','Vertex Pharmaceuticals','Healthcare',['sp500','ndx']],
  ['C','Citigroup','Financials',['sp500']],
  ['MU','Micron Technology','Semiconductors',['sp500','ndx']],
  ['MDT','Medtronic','Healthcare',['sp500']],
  ['ADI','Analog Devices','Semiconductors',['sp500','ndx']],
  ['GILD','Gilead Sciences','Healthcare',['sp500','ndx']],
  ['BSX','Boston Scientific','Healthcare',['sp500']],
  ['LRCX','Lam Research','Semiconductors',['sp500','ndx']],
  ['BMY','Bristol-Myers','Healthcare',['sp500']],
  ['REGN','Regeneron','Healthcare',['sp500','ndx']],
  ['MDLZ','Mondelez','Consumer Staples',['sp500','ndx']],
  ['INTC','Intel','Semiconductors',['sp500','ndx']],
  ['ANET','Arista Networks','Technology',['sp500']],
  ['FI','Fiserv','Financials',['sp500']],
  ['PANW','Palo Alto Networks','Technology',['sp500','ndx']],
  ['CI','Cigna','Healthcare',['sp500']],
  ['KLAC','KLA','Semiconductors',['sp500','ndx']],
  ['SO','Southern Co','Utilities',['sp500']],
  ['BA','Boeing','Industrials',['sp500','dow']],
  ['EQIX','Equinix','Real Estate',['sp500','ndx']],
  ['CRWD','CrowdStrike','Technology',['sp500','ndx']],
  ['ZTS','Zoetis','Healthcare',['sp500']],
  ['MMC','Marsh McLennan','Financials',['sp500']],
  ['PH','Parker-Hannifin','Industrials',['sp500']],
  ['DUK','Duke Energy','Utilities',['sp500']],
  ['SHW','Sherwin-Williams','Materials',['sp500','dow']],
  ['AON','Aon','Financials',['sp500']],
  ['CMG','Chipotle','Consumer Discretionary',['sp500']],
  ['ICE','Intercontinental Exchange','Financials',['sp500']],
  ['WM','Waste Management','Industrials',['sp500']],
  ['TT','Trane Technologies','Industrials',['sp500']],
  ['USB','US Bancorp','Financials',['sp500']],
  ['PNC','PNC Financial','Financials',['sp500']],
  ['APH','Amphenol','Technology',['sp500']],
  ['MCO',"Moody's",'Financials',['sp500']],
  ['ITW','Illinois Tool Works','Industrials',['sp500']],
  ['CL','Colgate-Palmolive','Consumer Staples',['sp500']],
  ['TGT','Target','Consumer Discretionary',['sp500']],
  ['MMM','3M','Industrials',['sp500']],
  ['CDNS','Cadence Design','Technology',['sp500','ndx']],
  ['SNPS','Synopsys','Technology',['sp500','ndx']],
  ['MCK','McKesson','Healthcare',['sp500']],
  ['GD','General Dynamics','Industrials',['sp500']],
  ['EMR','Emerson Electric','Industrials',['sp500']],
  ['NOC','Northrop Grumman','Industrials',['sp500']],
  ['CME','CME Group','Financials',['sp500']],
  ['FCX','Freeport-McMoRan','Materials',['sp500']],
  ['WELL','Welltower','Real Estate',['sp500']],
  ['FDX','FedEx','Industrials',['sp500']],
  ['APD','Air Products','Materials',['sp500']],
  ['MAR','Marriott','Consumer Discretionary',['sp500','ndx']],
  ['CSX','CSX','Industrials',['sp500','ndx']],
  ['COF','Capital One','Financials',['sp500']],
  ['CARR','Carrier Global','Industrials',['sp500']],
  ['FTNT','Fortinet','Technology',['sp500','ndx']],
  ['ECL','Ecolab','Materials',['sp500']],
  ['ADSK','Autodesk','Technology',['sp500','ndx']],
  ['ORLY',"O'Reilly Auto",'Consumer Discretionary',['sp500','ndx']],
  ['AJG','Arthur J. Gallagher','Financials',['sp500']],
  ['SLB','Schlumberger','Energy',['sp500']],
  ['PYPL','PayPal','Financials',['sp500','ndx']],
  ['NXPI','NXP Semiconductors','Semiconductors',['sp500','ndx']],
  ['AZO','AutoZone','Consumer Discretionary',['sp500']],
  ['HLT','Hilton','Consumer Discretionary',['sp500']],
  ['BDX','Becton Dickinson','Healthcare',['sp500']],
  ['ROP','Roper Technologies','Technology',['sp500']],
  ['TFC','Truist Financial','Financials',['sp500']],
  ['DLR','Digital Realty','Real Estate',['sp500']],
  ['NSC','Norfolk Southern','Industrials',['sp500']],
  ['O','Realty Income','Real Estate',['sp500']],
  ['BK','Bank of New York Mellon','Financials',['sp500']],
  ['EOG','EOG Resources','Energy',['sp500']],
  ['GM','General Motors','Consumer Discretionary',['sp500']],
  ['F','Ford','Consumer Discretionary',['sp500']],
  ['SRE','Sempra','Utilities',['sp500']],
  ['AMT','American Tower','Real Estate',['sp500']],
  ['PLD','Prologis','Real Estate',['sp500']],
  ['MO','Altria','Consumer Staples',['sp500']],
  ['HCA','HCA Healthcare','Healthcare',['sp500']],
  ['URI','United Rentals','Industrials',['sp500']],
  ['VLO','Valero Energy','Energy',['sp500']],
  ['AIG','American International Group','Financials',['sp500']],
  ['MPC','Marathon Petroleum','Energy',['sp500']],
  ['MSI','Motorola Solutions','Technology',['sp500']],
  ['PSX','Phillips 66','Energy',['sp500']],
  ['KMB','Kimberly-Clark','Consumer Staples',['sp500']],
  ['GWW','W.W. Grainger','Industrials',['sp500']],
  ['CMI','Cummins','Industrials',['sp500']],
  ['WMB','Williams Companies','Energy',['sp500']],
  ['AEP','American Electric Power','Utilities',['sp500']],
  ['PSA','Public Storage','Real Estate',['sp500']],
  ['AFL','Aflac','Financials',['sp500']],
  ['MET','MetLife','Financials',['sp500']],
  ['ALL','Allstate','Financials',['sp500']],
  ['TRV','Travelers','Financials',['sp500','dow']],
  ['FIS','Fidelity National Info','Financials',['sp500']],
  ['SBUX','Starbucks','Consumer Discretionary',['sp500','ndx']],
  ['CHTR','Charter Communications','Communication',['sp500','ndx']],
  ['NKE','Nike','Consumer Discretionary',['sp500','dow']],
  ['KMI','Kinder Morgan','Energy',['sp500']],
  ['OKE','ONEOK','Energy',['sp500']],
  ['JCI','Johnson Controls','Industrials',['sp500']],
  ['PCAR','PACCAR','Industrials',['sp500','ndx']],
  ['PAYX','Paychex','Industrials',['sp500','ndx']],
  ['ROST','Ross Stores','Consumer Discretionary',['sp500','ndx']],
  ['ABNB','Airbnb','Consumer Discretionary',['sp500','ndx']],
  ['MNST','Monster Beverage','Consumer Staples',['sp500','ndx']],
  ['DASH','DoorDash','Consumer Discretionary',['sp500','ndx']],
  ['ADM','Archer-Daniels-Midland','Consumer Staples',['sp500']],
  ['GIS','General Mills','Consumer Staples',['sp500']],
  ['HSY','Hershey','Consumer Staples',['sp500']],
  ['SYY','Sysco','Consumer Staples',['sp500']],
  ['KHC','Kraft Heinz','Consumer Staples',['sp500','ndx']],
  ['MRNA','Moderna','Healthcare',['sp500','ndx']],
  ['DXCM','DexCom','Healthcare',['sp500','ndx']],
  ['AMAT','Applied Materials','Semiconductors',['sp500','ndx']],
  ['ASML','ASML Holding','Semiconductors',['sp500','ndx']],
  ['MRVL','Marvell Technology','Semiconductors',['sp500','ndx']],
  ['ON','ON Semiconductor','Semiconductors',['sp500','ndx']],
  ['WDAY','Workday','Technology',['sp500','ndx']],
  ['TEAM','Atlassian','Technology',['sp500','ndx']],
  ['DDOG','Datadog','Technology',['sp500','ndx']],
  ['ZS','Zscaler','Technology',['sp500','ndx']],
  ['OKTA','Okta','Technology',['sp500','ndx']],
  ['NET','Cloudflare','Technology',['sp500']],
  ['SNOW','Snowflake','Technology',['sp500']],
  ['DOCU','DocuSign','Technology',['sp500']],
  ['MDB','MongoDB','Technology',['sp500']],
  ['HUBS','HubSpot','Technology',['sp500']],
  ['EXC','Exelon','Utilities',['sp500','ndx']],
  ['XEL','Xcel Energy','Utilities',['sp500','ndx']],
  ['ED','Consolidated Edison','Utilities',['sp500']],
  ['D','Dominion Energy','Utilities',['sp500']],
  ['PCG','PG&E','Utilities',['sp500']],
  // Russell 2000 top 250
  ['SMCI','Super Micro Computer','Technology',['russell2k']],
  ['SMTC','Semtech','Semiconductors',['russell2k']],
  ['AR','Antero Resources','Energy',['russell2k']],
  ['MTZ','MasTec','Industrials',['russell2k']],
  ['CHX','ChampionX','Energy',['russell2k']],
  ['MUR','Murphy Oil','Energy',['russell2k']],
  ['CHRD','Chord Energy','Energy',['russell2k']],
  ['CNX','CNX Resources','Energy',['russell2k']],
  ['PR','Permian Resources','Energy',['russell2k']],
  ['MGY','Magnolia Oil & Gas','Energy',['russell2k']],
  ['NOG','Northern Oil and Gas','Energy',['russell2k']],
  ['BTU','Peabody Energy','Energy',['russell2k']],
  ['ARCH','Arch Resources','Energy',['russell2k']],
  ['HCC','Warrior Met Coal','Materials',['russell2k']],
  ['HALO','Halozyme Therapeutics','Healthcare',['russell2k']],
  ['VKTX','Viking Therapeutics','Healthcare',['russell2k']],
  ['ARWR','Arrowhead Pharmaceuticals','Healthcare',['russell2k']],
  ['ACAD','ACADIA Pharmaceuticals','Healthcare',['russell2k']],
  ['TGTX','TG Therapeutics','Healthcare',['russell2k']],
  ['IONS','Ionis Pharmaceuticals','Healthcare',['russell2k']],
  ['BPMC','Blueprint Medicines','Healthcare',['russell2k']],
  ['KRYS','Krystal Biotech','Healthcare',['russell2k']],
  ['RARE','Ultragenyx Pharmaceutical','Healthcare',['russell2k']],
  ['PCVX','Vaxcyte','Healthcare',['russell2k']],
  ['LEGN','Legend Biotech','Healthcare',['russell2k']],
  ['ADMA','ADMA Biologics','Healthcare',['russell2k']],
  ['CORT','Corcept Therapeutics','Healthcare',['russell2k']],
  ['HIMS','Hims & Hers Health','Healthcare',['russell2k']],
  ['CPRX','Catalyst Pharmaceuticals','Healthcare',['russell2k']],
  ['LNTH','Lantheus Holdings','Healthcare',['russell2k']],
  ['TMDX','TransMedics Group','Healthcare',['russell2k']],
  ['PEN','Penumbra','Healthcare',['russell2k']],
  ['RYTM','Rhythm Pharmaceuticals','Healthcare',['russell2k']],
  ['CYTK','Cytokinetics','Healthcare',['russell2k']],
  ['APLS','Apellis Pharmaceuticals','Healthcare',['russell2k']],
  ['ALNY','Alnylam Pharmaceuticals','Healthcare',['russell2k']],
  ['EXEL','Exelixis','Healthcare',['russell2k']],
  ['NTRA','Natera','Healthcare',['russell2k']],
  ['JAZZ','Jazz Pharmaceuticals','Healthcare',['russell2k']],
  ['ALKS','Alkermes','Healthcare',['russell2k']],
  ['PTCT','PTC Therapeutics','Healthcare',['russell2k']],
  ['USFD','US Foods','Consumer Staples',['russell2k']],
  ['PFGC','Performance Food Group','Consumer Staples',['russell2k']],
  ['SFM','Sprouts Farmers Market','Consumer Staples',['russell2k']],
  ['BJ',"BJ's Wholesale Club",'Consumer Staples',['russell2k']],
  ['POST','Post Holdings','Consumer Staples',['russell2k']],
  ['TAP','Molson Coors Beverage','Consumer Staples',['russell2k']],
  ['DECK','Deckers Outdoor','Consumer Discretionary',['russell2k']],
  ['CROX','Crocs','Consumer Discretionary',['russell2k']],
  ['BOOT','Boot Barn Holdings','Consumer Discretionary',['russell2k']],
  ['ANF','Abercrombie & Fitch','Consumer Discretionary',['russell2k']],
  ['URBN','Urban Outfitters','Consumer Discretionary',['russell2k']],
  ['AEO','American Eagle Outfitters','Consumer Discretionary',['russell2k']],
  ['RH','RH','Consumer Discretionary',['russell2k']],
  ['WSM','Williams-Sonoma','Consumer Discretionary',['russell2k']],
  ['LEVI','Levi Strauss','Consumer Discretionary',['russell2k']],
  ['YETI','YETI Holdings','Consumer Discretionary',['russell2k']],
  ['PLNT','Planet Fitness','Consumer Discretionary',['russell2k']],
  ['TXRH','Texas Roadhouse','Consumer Discretionary',['russell2k']],
  ['WING','Wingstop','Consumer Discretionary',['russell2k']],
  ['SHAK','Shake Shack','Consumer Discretionary',['russell2k']],
  ['CAKE','Cheesecake Factory','Consumer Discretionary',['russell2k']],
  ['EAT','Brinker International','Consumer Discretionary',['russell2k']],
  ['BLD','TopBuild','Industrials',['russell2k']],
  ['TPX','Tempur Sealy','Consumer Discretionary',['russell2k']],
  ['UPST','Upstart Holdings','Financials',['russell2k']],
  ['SOFI','SoFi Technologies','Financials',['russell2k']],
  ['AFRM','Affirm Holdings','Financials',['russell2k']],
  ['HOOD','Robinhood Markets','Financials',['russell2k']],
  ['LMND','Lemonade','Financials',['russell2k']],
  ['ESNT','Essent Group','Financials',['russell2k']],
  ['MTG','MGIC Investment','Financials',['russell2k']],
  ['RDN','Radian Group','Financials',['russell2k']],
  ['PFSI','PennyMac Financial','Financials',['russell2k']],
  ['RITM','Rithm Capital','Financials',['russell2k']],
  ['AGNC','AGNC Investment','Real Estate',['russell2k']],
  ['NLY','Annaly Capital','Real Estate',['russell2k']],
  ['STWD','Starwood Property Trust','Real Estate',['russell2k']],
  ['BXMT','Blackstone Mortgage Trust','Real Estate',['russell2k']],
  ['APLE','Apple Hospitality REIT','Real Estate',['russell2k']],
  ['EPR','EPR Properties','Real Estate',['russell2k']],
  ['OHI','Omega Healthcare Investors','Real Estate',['russell2k']],
  ['NSA','National Storage Affiliates','Real Estate',['russell2k']],
  ['STAG','STAG Industrial','Real Estate',['russell2k']],
  ['CUZ','Cousins Properties','Real Estate',['russell2k']],
  ['KRC','Kilroy Realty','Real Estate',['russell2k']],
  ['IRT','Independence Realty Trust','Real Estate',['russell2k']],
  ['AXTA','Axalta Coating Systems','Materials',['russell2k']],
  ['OLN','Olin','Materials',['russell2k']],
  ['HUN','Huntsman','Materials',['russell2k']],
  ['WLK','Westlake','Materials',['russell2k']],
  ['RPM','RPM International','Materials',['russell2k']],
  ['MP','MP Materials','Materials',['russell2k']],
  ['HWM','Howmet Aerospace','Industrials',['russell2k']],
  ['AXON','Axon Enterprise','Industrials',['russell2k']],
  ['BLDR','Builders FirstSource','Industrials',['russell2k']],
  ['GGG','Graco','Industrials',['russell2k']],
  ['SAIA','Saia','Industrials',['russell2k']],
  ['XPO','XPO','Industrials',['russell2k']],
  ['ARCB','ArcBest','Industrials',['russell2k']],
  ['KNX','Knight-Swift Transportation','Industrials',['russell2k']],
  ['ACM','AECOM','Industrials',['russell2k']],
  ['EME','EMCOR Group','Industrials',['russell2k']],
  ['PWR','Quanta Services','Industrials',['russell2k']],
  ['PRIM','Primoris Services','Industrials',['russell2k']],
  ['BWXT','BWX Technologies','Industrials',['russell2k']],
  ['HEI','HEICO','Industrials',['russell2k']],
  ['RKLB','Rocket Lab','Industrials',['russell2k']],
  ['ACHR','Archer Aviation','Industrials',['russell2k']],
  ['JOBY','Joby Aviation','Industrials',['russell2k']],
  ['PLUG','Plug Power','Industrials',['russell2k']],
  ['BE','Bloom Energy','Industrials',['russell2k']],
  ['RUN','Sunrun','Industrials',['russell2k']],
  ['ENPH','Enphase Energy','Industrials',['russell2k']],
  ['SEDG','SolarEdge Technologies','Industrials',['russell2k']],
  ['FSLR','First Solar','Industrials',['russell2k']],
  ['IOT','Samsara','Technology',['russell2k']],
  ['MSTR','MicroStrategy','Technology',['russell2k']],
  ['RBLX','Roblox','Communication',['russell2k']],
  ['APP','AppLovin','Technology',['russell2k']],
  ['DUOL','Duolingo','Technology',['russell2k']],
  ['PATH','UiPath','Technology',['russell2k']],
  ['GTLB','GitLab','Technology',['russell2k']],
  ['CFLT','Confluent','Technology',['russell2k']],
  ['DOCN','DigitalOcean','Technology',['russell2k']],
  ['ESTC','Elastic','Technology',['russell2k']],
  ['RIVN','Rivian Automotive','Consumer Discretionary',['russell2k']],
  ['LCID','Lucid Group','Consumer Discretionary',['russell2k']],
  ['CHPT','ChargePoint','Industrials',['russell2k']],
  ['CRSP','CRISPR Therapeutics','Healthcare',['russell2k']],
  ['NTLA','Intellia Therapeutics','Healthcare',['russell2k']],
  ['BEAM','Beam Therapeutics','Healthcare',['russell2k']],
  ['EDIT','Editas Medicine','Healthcare',['russell2k']],
  ['RXRX','Recursion Pharmaceuticals','Healthcare',['russell2k']],
  ['TEM','Tempus AI','Healthcare',['russell2k']],
  ['IONQ','IonQ','Technology',['russell2k']],
  ['QBTS','D-Wave Quantum','Technology',['russell2k']],
  ['SYM','Symbotic','Industrials',['russell2k']],
  ['SOUN','SoundHound AI','Technology',['russell2k']],
  ['AI','C3.ai','Technology',['russell2k']],
  ['TER','Teradyne','Semiconductors',['russell2k']],
  ['ENTG','Entegris','Semiconductors',['russell2k']],
  ['MPWR','Monolithic Power Systems','Semiconductors',['russell2k']],
  ['ONTO','Onto Innovation','Semiconductors',['russell2k']],
  ['RMBS','Rambus','Semiconductors',['russell2k']],
  ['POWI','Power Integrations','Semiconductors',['russell2k']],
  ['WOLF','Wolfspeed','Semiconductors',['russell2k']],
  ['ACLS','Axcelis Technologies','Semiconductors',['russell2k']],
  ['FORM','FormFactor','Semiconductors',['russell2k']],
  ['COHR','Coherent','Technology',['russell2k']],
  ['FLEX','Flex','Technology',['russell2k']],
  ['JBL','Jabil','Technology',['russell2k']],
  ['VRT','Vertiv Holdings','Industrials',['russell2k']],
  ['XYL','Xylem','Industrials',['russell2k']],
  ['PNR','Pentair','Industrials',['russell2k']],
  ['CLH','Clean Harbors','Industrials',['russell2k']],
  ['KBR','KBR','Industrials',['russell2k']],
  ['CELH','Celsius Holdings','Consumer Staples',['russell2k']],
  ['FRPT','Freshpet','Consumer Staples',['russell2k']],
  ['BRBR','BellRing Brands','Consumer Staples',['russell2k']],
  ['SMPL','Simply Good Foods','Consumer Staples',['russell2k']],
  ['CW','Curtiss-Wright','Industrials',['russell2k']],
  ['CRUS','Cirrus Logic','Semiconductors',['russell2k']],
  ['SWKS','Skyworks Solutions','Semiconductors',['russell2k']],
  ['QRVO','Qorvo','Semiconductors',['russell2k']],
  ['CRDO','Credo Technology','Semiconductors',['russell2k']],
  ['ALGM','Allegro MicroSystems','Semiconductors',['russell2k']],
];

export const UNIVERSE: UniverseEntry[] = ROWS.map(
  ([ticker, name, sector, indices]) => ({ ticker, name, sector, indices }),
);

export const inIndex = (tag: IndexTag) =>
  UNIVERSE.filter((u) => u.indices.includes(tag));

export const findEntry = (ticker: string): UniverseEntry | undefined =>
  UNIVERSE.find((u) => u.ticker === ticker);

// Core watchlist (30 names) used when no filter is specified — high-quality
// liquid names that cover all sectors for daily board generation.
export const CORE_WATCHLIST: string[] = [
  'NVDA','AAPL','MSFT','GOOGL','AMZN','META','TSLA','AVGO','AMD','INTC',
  'JPM','BAC','GS','MS','V','MA',
  'UNH','LLY','JNJ','ABBV',
  'XOM','CVX','COP',
  'WMT','COST','PG','KO',
  'HD','LOW',
  'NFLX','DIS','CRM','ORCL',
];
